import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import { PublicEnvScript } from "next-runtime-env";
import TanstackQueryProvider from "@/components/provider/tanstack-query-provider";
import "./globals.css";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Console Please Scan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <PublicEnvScript />
      </head>
      <body className={`${notoSansThai.variable} antialiased`}>
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  );
}
