import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import { PublicEnvScript } from "next-runtime-env";
import TanstackQueryProvider from "@/components/provider/tanstack-query-provider";
import "./globals.css";
import { cookies } from "next/headers";
import initTranslations, { i18nNamespaces } from "@/lib/i18n/i18n";
import TranslationsProvider from "@/components/provider/translations-provider";
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from "sonner";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai", "latin"],
});

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Console Please Scan",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const locals = cookiesStore.get("i18next")?.value || "en";
  const { resources } = await initTranslations(locals, i18nNamespaces);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <PublicEnvScript />
      </head>
      <body className={`${notoSansThai.variable} antialiased`}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locals}
          resources={resources}
        >
          <TanstackQueryProvider>
            <NuqsAdapter>
              <Toaster expand richColors position="top-center" />
              {children}
            </NuqsAdapter>
          </TanstackQueryProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
